### ISSUE TITLE
ubuntu-osdeps-{humble,jazzy} defines some packages only for outdated distros and wrongfully overwrite some autoproj-default osdeps

### ISSUE THREAD

**Issue by chhtz** [dfki-ric/ros2-package_set#12]
Examples ("bionic" is Ubuntu 18.04):
```
python:
    ubuntu:
        bionic: ["python-dev"]
```
python is previously defined by autoproj/default.osdeps:
```
      arch: python2
      debian:
        8,jessie,9,stretch: python-dev
        default: python3-dev
      ubuntu:
        16.04,18.04: python-dev
        default: python3-dev
      fedora: python-devel
      freebsd: python-devel
      gentoo: dev-lang/python
      opensuse: python-devel
      default: ignore
```

Another example:
```
python-setuptools:
    ubuntu:
        bionic: ["python-setuptools"]
```

There are valid corresponding definitions with `python3` instead of `python`, but several packages have dependencies on `python-*`, notably every `python_package` implicitly depends on `python`, so I guess we should just make them equivalent (i.e., always install the python3 variant).
